### ISSUE TITLE
No info.list

### ISSUE THREAD

**Issue by JasonLiuOrg** [samiamwork/Movist#50]
I used the Xcode 7.3 to open this project. There is the info.list in the project,but there is an issue:' sed: /Users/Jincheng/Library/Developer/Xcode/DerivedData/Movist-goxkwddcexbaipbldxfcczytzraw/Build/Products/Debug/Movist.app/Contents/Info.plist: No such file or directory'

**Comment by samiamwork** [comment]
It looks like Xcode was running one of the build phases out of order. I've just pushed a fix for this (e5c3bb90dc28b95d8c3a) so that it builds. That should get it building. Unfortunately I'm still seeing some problems when running on 10.11 ("Fallingback to pbuffer" and bad scaling in the video view) but at least it builds and runs. If you want to try fixing the other issues that would be great. I don't expect them to be that hard to fix, I just won't have time to investigate for a while.
