### ISSUE TITLE
Request to now how to select from multiple ffmpeg installations on machines

### ISSUE THREAD

**Issue by davidfavor** [samiamwork/Movist#52]
I have two ffmpeg installations...
```
imac> wg ffmpeg
/runtime/osx-10.11/bin/ffmpeg
/opt/local/bin/ffmpeg
```
Let me know best way to select a specific installation.

Thanks.

**Comment by davidfavor** [comment]
Looks like somehow the source files of the alternative distro must be plumbed into the Movist source file hierarchy...

Maybe overwriting contrib/libav with another set of source.

Be great if someone can add a comment about the correct way to accomplish plumbing in a new version of ffmpeg, so new codes like HEVC can be injected into Movist.

**Comment by samiamwork** [comment]
Yeah, it's locked to a specific version of libav (via submodules) to prevent it from picking up whatever version might be on your system and to make the builds reproducible. Updating to a new version works like this:
- Go into contrib/libav and do `git fetch` to get the latest remote versions of the source.
- Check out the code to whatever more recent version you want to use. (I always use tagged releases)
- Build (all the scripts are expecting to be called from Xcode so just do all your building from there. Xcode should show you any errors.
- Find all the errors and warnings due to API changes and fix them. Fortunately they're good about deprecating first and then removing and documenting what the replacement is. It should all be in the headers. This might be a pain since it's been so long since I updated.

Again, sorry for the late reply! I'll try to commit these instructions to the README or something.

**Comment by samiamwork** [comment]
Added these directions to the README.
