### ISSUE TITLE
First time XCode build, where's the executable

### ISSUE THREAD

**Issue by davidfavor** [samiamwork/Movist#54]
I normally use command line tools. First time using XCode.

I have a successful build now (thanks for the previous fixes).

Command I issued was Xcode -> Project -> Build.

Let me know next commands required to create Movist.app for installation.

Be great if you added this info to the home page of project too.

Thanks.

**Comment by samiamwork** [comment]
Easiest way to explain is to select "Archive" from the "Product" menu. Then open then "Organizer" window from the "Window" menu. Click "Distribute App" and pick "Copy App". There are easier ways but oddly I find this easier to explain.

I don't want to add it to the README because Xcode has it's own documentation and users are better served by reading that.
