### ISSUE TITLE
Is there an easy way to make this portable

### ISSUE THREAD

**Issue by phirestalker** [samiamwork/Movist#56]
It would be great to have the application store all the preferences and any traces in its own folder. That way it could be stored on a USB and leave nothing behind on the host computer. Is this possible even with mac. I know Apple are a bunch of sneaky SOBs.

**Comment by samiamwork** [comment]
Anything's possible but I don't know of an easy way. Because of app bundles MacOS apps are already really portable. If someone has a good way to do this though I'm not opposed. Pretty much the only thing running Movist will leave behind is preferences. It's probably best not to muck with how preferences work though.

Is there a specific reason you want it to work this way?
